### PR TITLE
Port #237 to rawhide branch

### PR DESCRIPTION
**Pull request by jan-cerny**
This ports https://github.com/OpenSCAP/oscap-anaconda-addon/pull/237 to `rawhide` branch.

I'm unable to say if it works or not. How can I test this? The steps in the Developer guide suggests using `reanaconda`, but `reanaconda prime` fails with a traceback when I try to pass a Fedora rawhide URL installation tree.

### CODE REVIEW

**Comment by matejak** [comment]
First of all, the test fails for reasons that should be fixable in the PR.

Regarding integration testing, a downloaded Fedora image + specifying `inst.updates=http://...` in the VM works, although it is much more cumbersome. However, the Fedora `os` tree is something else than the RHEL tree, so it is hard to say whether it can even be fixed.

**Comment by jan-cerny** [comment]
@jan-cerny Thanks for suggestion. I believe we should update the developer documentation then.

**Comment by jan-cerny** [comment]
I have fixed the failed unit test, I have rebased this PR on the top of the `rawhide` branch and I have also successfully executed it in the Fedora install on the Fedora Server 38 installation DVD iso.

**Comment by jan-cerny** [comment]
The CI fail is unrelated to the contents of this PR because we can see the same CI fail in #245 , it looks like the job is broken in general. Any thoughts?

**Comment by jan-cerny** [comment]
The CI fail seems related to #238.

**Comment by matejak** [comment]
Please try to rebase, tests should pass now.

**Pull request closed without merging**
