### PR TITLE
Updated code to comply to the Bootloader proxy API.

### PR DESCRIPTION
**Pull request by matejak**
@jkonecny12 Could you please check this out?

### CODE REVIEW

**Comment by matejak** [comment]
Thank you, we will proceed.

**Comment by jan-cerny** [comment]
Hi @matejak , what remains here to be done?

**Comment by matejak** [comment]
IMO nothing, I was not able to reproduce the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1664036 any more.

**Comment by jan-cerny** [comment]
@matejak Does that mean that this PR fully fixes the BZ ?

**Comment by matejak** [comment]
@jan-cerny Yes, it looks like that.

**Comment by jan-cerny** [comment]
I usually like to reference a BZ in the commit message of the commit that fixes the bug, eg.:
`RHBZ#1664036: Use Bootloader proxy API`.

**Pull request merged**
