### PR TITLE
GH Actions: Init with unittest

### PR DESCRIPTION
**Pull request by evgenyz**

### CODE REVIEW

**Comment by matejak** [comment]
This looks good, but we will need to be able to adjust a branch-Fedora version mapping somehow. For example, the `master` branch corresponds to rawhide, and `rhel9` to 34 for the time being.

**Comment by evgenyz** [comment]
> This looks good, but we will need to be able to adjust a branch-Fedora version mapping somehow. For example, the `master` branch corresponds to rawhide, and `rhel9` to 34 for the time being.

What about rhel8? F33?

**Comment by evgenyz** [comment]
The best I could come up with ATM.

**Comment by matejak** [comment]
So rawhide is not a good target, as even casual packages don't have to be installable there every day, and I have estimated Fedora 32 to be a good choice for the rhel8-branch.
I am merging this, the rest of settings looks reasonable, thanks for the investigation and effort!

**Review by matejak — APPROVED** [review]

**Pull request merged**
