### PR TITLE
Add PR template

### PR DESCRIPTION
**Pull request by jan-cerny**
The template will help PR authors to make their PRs easily reviewable and will guide them to ensure the greatest transparency during PR contribution. The template is based on the template used in the ComplianceAsCode/content repository.

### CODE REVIEW

**Comment by matejak** [comment]
LGTM, but will the template be picked up if it lives in the rhel8-branch?

**Review by matejak — APPROVED** [review]

**Comment by jan-cerny** [comment]
@matejak It was to provide ideas because people want to discuss and this PR has been proposed instead of a separate meeting.

> LGTM, but will the template be picked up if it lives in the rhel8-branch?

No idea. How do we find out?

**Comment by jan-cerny** [comment]
FYI this says this needs to be the default branch: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

Which branch is default?

**Comment by matejak** [comment]
This one, but please also port it to other ones, as the `rhel8-branch` will not be default forever.

**Pull request merged**
