### PR TITLE
Update Makefile to handle python2 and python3 tests

### PR DESCRIPTION
**Pull request by redhatrises**
- Makefile checks if OS is Red Hat Enterprise Linux 7 for python2 tests. If not, uses python3 tests

### CODE REVIEW

**Comment by dahaic** [comment]
Jenkins test this please.

**Comment by dahaic** [comment]
Jenkins test this please.

**Comment by redhatrises** [comment]
@dahaic the fedora test is expected to fail.

**Comment by dahaic** [comment]
Failures are expected, ACK.

**Pull request merged**
