### PR TITLE
These patches made it into master, but not rhel7-branch.

### PR DESCRIPTION
**Pull request by jcpunk**
Since most of the work seems to be happening in rhel7-branch, I didn't want these to get lost over time.

### CODE REVIEW

**Comment by mpreisler** [comment]
Hi @jcpunk 

I think it might be a good idea to backport these but could we please get the original commit references and commit messages? git cherry-pick should give that to us.

**Comment by jcpunk** [comment]
Given how much the rhel7 branch has drifted from master, might it make more sense to merge the branch into master?

**Comment by redhatrises** [comment]
Closing this as #27 and #28 have been merged.

**Comment by mpreisler** [comment]
For the record I have merged all fixes from `rhel7-branch` into `master` so we should be more or less in sync now. Please do bugfixes in `rhel7-branch` and breaking changes in `master` from now on.

**Pull request closed without merging**
