### PR TITLE
Replace "policy" with "profile"

### PR DESCRIPTION
**Pull request by redhatrises**
- OAA applies security profiles and not security policy. Security policy is more than what OAA supports, and the policy specifies what profile to use (e.g. stig, cis, etc.) and customization to make to those profiles. This fixes that misnomer.

### CODE REVIEW

**Comment by matejak** [comment]
Have you considered proposing that change against `master`? A change of terminology is not really a typo, and although I agree that it is a change in right direction, I would keep the current name for RHEL8.

**Comment by redhatrises** [comment]
> Have you considered proposing that change against `master`? A change of terminology is not really a typo, and although I agree that it is a change in right direction, I would keep the current name for RHEL8.

If you would prefer it under master, then sure.

**Comment by matejak** [comment]
Yes, please, that would be great.

**Comment by redhatrises** [comment]
See #130

**Pull request closed without merging**
