### PR TITLE
Document testing of OAA with KS

### PR DESCRIPTION
**Pull request by jan-cerny**
Add #191 and #193 to rhel9 branch.

### CODE REVIEW

**Comment by jan-cerny** [comment]
Hello everyone, to clarify, this PR is only a port of already merged PRs to the rhel9 branch.

**Review by matejak — CHANGES_REQUESTED** [review]
Great work, thanks!
However, please replace the RHEL8 ks with RHEL9 ks - it's about the filename and RHEL8 references.

**Comment by jan-cerny** [comment]
changed

**Review by matejak — APPROVED** [review]

**Comment by matejak** [comment]
LGTM, thanks!

**Pull request merged**
