### PR TITLE
Test rpm extraction

### PR DESCRIPTION
**Pull request by yuumasato**
- Add tests for extraction of rpm content.
- RPM binaries for testing included.
- Fix a bug when loading an RPM with paths to directories listed.

### CODE REVIEW

**Comment by yuumasato** [comment]
Unfortunately these tests will be failing until this [patch](https://src.fedoraproject.org/rpms/python-cpio/pull-request/2#) gets merged and built downstream.

**Comment by matejak** [comment]
Also testing nodes have to be updated with Fedora 29.

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
@yuumasato A RHEL8 branch has been introduced to this repo as RHEL8-incompatible changes are on their way, so I would say that after test pass, change the target of this PR to RHEL8.

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
So now those test failures look interesting.

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
Great work, thank you for improving the test suite!

**Pull request merged**
