### PR TITLE
remove xccdf-path configuration option which can overwrite content-path

### PR DESCRIPTION
**Pull request by dardok**

### CODE REVIEW

**Comment by redhatrises** [comment]
@openscap-ci add to whitelist

**Comment by redhatrises** [comment]
@dardok xccdf-path is provided so that the content path can be overwritten.

**Comment by dardok** [comment]
Oh, sorry - thought it was a typo, I accidentally used it with a -xccdf file *and* content-path set to a -ds and was confused as to why it ended up running the eval against the xccdf.  Rescinding...

**Comment by redhatrises** [comment]
@dardok no worries :)

**Pull request closed without merging**
